apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: registry.uffizzi.com/quickstart
      context: ./src
      sync:
        manual:
          - src: ./src
            dest: /app
manifests:
  rawYaml:
    - k8s/web.yaml
